apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-tweet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linux-tweet-app
  template:
    metadata:
      labels:
        app: linux-tweet-app
    spec:
      containers:
        - name: schoolonair-cms
          image: 969220108910.dkr.ecr.us-east-1.amazonaws.com/linux-tweet-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always