apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-tweet-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: linux-tweet-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: linux-tweet-app
    spec:
      containers:
      - name: schoolonair-cms
        image: 969220108910.dkr.ecr.us-east-1.amazonaws.com/linux-tweet-app:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
      restartPolicy: Always