apiVersion: v1
kind: Service
metadata:
  name: linux-tweet-app
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: linux-tweet-app