version: 2
jobs:
  linting:
    docker:
    - image: alpine:3.16
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          apk update && apk add make
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
          chmod +x /bin/hadolint
    - run:
        name: Check Dockerfile syntax
        command: make lint
  build:
    docker:
    - image: alpine:3.16
    environment:
      CONTAINER_REGISTRY_URI: 969220108910.dkr.ecr.us-east-1.amazonaws.com
    steps:
    - checkout
    - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true
    - run:
        name: Install dependencies
        command: |
          apk add --no-cache aws-cli docker-cli
    - run:
        name: Login ECR
        command: |
          aws ecr get-login-password \
            --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${CONTAINER_REGISTRY_URI}
    - run:
        name: Build docker image
        command: docker build -t linux-tweet-app:latest .
    - run:
        name: Create image tags
        command: |
          docker tag linux-tweet-app:latest $CONTAINER_REGISTRY_URI/linux-tweet-app:latest
          docker tag linux-tweet-app:latest $CONTAINER_REGISTRY_URI/linux-tweet-app:${CIRCLE_SHA1}
    - run:
        name: Push images
        command: |
          docker push $CONTAINER_REGISTRY_URI/linux-tweet-app:latest
          docker push $CONTAINER_REGISTRY_URI/linux-tweet-app:${CIRCLE_SHA1}
  deploy:
    docker:
    - image: ubuntu:20.04
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: |
          apt update
          apt install -y curl zip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    - run: aws eks update-kubeconfig --region us-east-1 --name LinuxTweetCluster
    - run: kubectl apply -f .circleci/manifests/

workflows:
  version: 2
  linux-tweet-app-workflow:
    jobs:
    - linting
    - build:
        filters:
          branches:
            only:
              - master
        requires:
          - "linting"
    - deploy:
        filters:
          branches:
            only:
              - master
        requires:
          - "build"